# Generated by Django 2.2.3 on 2019-07-30 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disposal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disposal',
            name='img',
        ),
    ]
