# Generated by Django 2.2.3 on 2019-07-31 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposal', '0002_remove_disposal_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposal',
            name='photo',
            field=models.ImageField(default='media/default_image.png', upload_to=''),
        ),
    ]
