# Generated by Django 2.2.3 on 2019-08-03 06:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('disposal', '0003_disposal_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposal',
            name='writer',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disposal',
            name='photo',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
